export const CHOOSE_CITY = 'CHOOSE_CITY';
export const SAVE_CITY = 'SAVE_CITY';
export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_REQUEST_SUCCESS = 'WEATHER_REQUEST_SUCCESS';
export const WEATHER_REQUEST_FAILURE = 'WEATHER_REQUEST_FAILURE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const ADD_WEATHER = 'ADD_WEATHER';
export const TIME_OUT = 300;
